theme = "blist"
languageCode = "en-US"
baseurl = "https://blist.vercel.app"
title = "Blist Theme"
themesDir = "themes"
baseURL = ""
publishDir = "public"

[params]
description = "Modern blog theme for your Hugo site."
name = "Blist Theme"
darkModeToggle = true
enableSearch = true
copyright = "Copyright © 2021 - Katheryn Fox · All rights reserved"
favicon = "favicon.svg"
ascentColor = "bg-blue-100"

  [params.homepage]
  title = "Hey! I'm Katheryn Fox"
  description = "26 y/o junior developer who enjoys social card games, blogging and painting"
  photo = "/picture.jpg"

    [params.homepage.social]
    title = "Follow me"
    description = "I work on everything coding and tweet developer memes"
    twitter = "https://twitter.com/"
    linkedin = "https://linkedin.com/in/"
    github = "https://github.com/"
    medium = "https://medium.com/"
    reddit = "https://reddit.com/"
    dribbble = "https://dribbble.com/"

[[menu.main]]
name = "About"
url = "/about"

[build]
writeStats = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup.highlight]
style = "dracula"

[markup.goldmark.renderer]
unsafe = true
